<a href="https://colab.research.google.com/github/Tulikash-09/Tensorflow/blob/main/Module_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Installing Tensorflow

In [1]:
%tensorflow_version 2.x

In [2]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


# Creating Tensors

**Rank 1 tensors (Scalar)**

In [3]:
string = tf.Variable("It's a string ",tf.string)
number = tf.Variable(29,tf.int64)
decimal = tf.Variable(3.56,tf.float64)

**Higher rank (dims) tensors**

In [5]:
ar1 = tf.Variable([2,5,7],tf.int64)
ar2 = tf.Variable([[5,3],[8,9]],tf.int64)

*Determing Rank*

In [6]:
tf.rank(ar2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

*Determing Shape*

In [7]:
ar1.shape

TensorShape([3])

*Reshaping the tensors*

In [8]:
t1 = tf.ones([2,3])
print(t1)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [11]:
t2 = tf.reshape(t1,[2,3,1])
print(t2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [12]:
t3 = tf.reshape(t2,[3,-1])
print(t3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


# Evaluating Tensors

In [16]:
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

tensor = tf.Variable(matrix, dtype=tf.int32)
print(tf.rank(tensor))
print(tensor.shape)

tf.Tensor(2, shape=(), dtype=int32)
(4, 5)


In [18]:
three = tensor[0,2]  # selects the 3rd element from the 1st row
print(three)  # -> 3

row1 = tensor[0]  # selects the first row
print(row1)

column1 = tensor[:, 0]  # selects the first column
print(column1)

row_2_and_4 = tensor[1::2]  # selects second and fourth row
print(row_2_and_4)

column_1_in_row_2_and_3 = tensor[1:3, 0]
print(column_1_in_row_2_and_3)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([ 1  6 11 16], shape=(4,), dtype=int32)
tf.Tensor(
[[ 6  7  8  9 10]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)
tf.Tensor([ 6 11], shape=(2,), dtype=int32)
